//
//  CreateRequestViewController.swift
//  MusicMas
//
//  Created by thomas anderson on 12/21/19.
//  Copyright (c) 2019 juan Andrés. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateRequestDisplayLogic: class
{
  func displaySomething(viewModel: CreateRequest.Something.ViewModel)
}

class CreateRequestViewController: UIViewController, CreateRequestDisplayLogic
{
    
      // MARK: Method call expectations
       var fetchMusicCalled = false
    
       // MARK: Spied methods
    /*   func fetchMusic(request: ListMusic_Request)
       {
         fetchMusicCalled = true
       }*/
    
  var interactor: CreateRequestBusinessLogic?
  var router: (NSObjectProtocol & CreateRequestRoutingLogic & CreateRequestDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CreateRequestInteractor()
    let presenter = CreateRequestPresenter()
    let router = CreateRequestRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = CreateRequest.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: CreateRequest.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
