//
//  CreateRequestModels.swift
//  MusicMas
//
//  Created by thomas anderson on 12/21/19.
//  Copyright (c) 2019 juan Andrés. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateRequest
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        var nombre: String?
    }
    struct Response
    {
        var ListaCanciones: [MusicData]?
        var isError: Bool?
        var message: String?
    }
    struct ViewModel
    {
        var ListaCanciones: [MusicData]?
    }
    struct ListMusic_Request{
        
    }
  }
}
